### ISSUE TITLE
Installing php54-mcrypt error—phpize: No such file or director

### ISSUE THREAD

**Issue by zakiwarfel** [Homebrew/homebrew-php#1262]
I'm trying to install PHP54-mcrypt using Homebrew and keep running into the following:

$ brew install php54-mcrypt
==> Downloading http://www.php.net/get/php-5.4.31.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php54-mcrypt-5.4.31
==> PHP_AUTOCONF="/usr/local/opt/autoconf/bin/autoconf" PHP_AUTOHEADER="/usr/local/opt/autoconf/bin/autohe
sh: /usr/local/Cellar/php54/5.4.31/bin/phpize: No such file or directory

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/josegonzalez/homebrew-php/issues

/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': Class is not a module (TypeError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:390:in `<class:HTTP>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:384:in `<module:Net>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:25:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/https.rb:21:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/utils.rb:308:in `open'
	from /usr/local/Library/Homebrew/utils.rb:350:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:378:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:171:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:167:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:207:in `dump'
	from /usr/local/Library/brew.rb:158:in `rescue in <main>'
	from /usr/local/Library/brew.rb:66:in `<main>'

**Comment by alanthing** [comment]
Closing due to inactivity from issue opener..
