### ISSUE TITLE
Unable to guess PHP branch for Formulary::Formulae::Php56Mcrypt

### ISSUE THREAD

**Issue by rnewton** [Homebrew/homebrew-php#1511]
I'm trying to add the mcrypt package to my PHP 5.6 install and I'm getting the error: 

````
Error: Unable to guess PHP branch for Formulary::Formulae::Php56Mcrypt
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:53:in `php_branch'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:58:in `php_formula'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:74:in `phpize'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:65:in `safe_phpize'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-mcrypt.rb:17:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:136:in `block in install'
/usr/local/Library/Homebrew/formula.rb:400:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:755:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:753:in `stage'
/usr/local/Library/Homebrew/formula.rb:396:in `brew'
/usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:185:in `<main>'
````

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.1
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.6.3
**Xcode Version:** | 6.1.1 (6A2008a)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn) Target: x86_64-apple-darwin14.0.0 Thread model: posix
**Output of php -v:** | PHP 5.6.3 (cli) (built: Dec 10 2014 14:52:44)  Copyright (c) 1997-2014 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
**Output of brew doctor** | Your system is ready to brew.

**Comment by rnewton** [comment]
Tried reinstalling php56 without issue: 

````
==> Reinstalling php56
==> Downloading https://www.php.net/get/php-5.6.3.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.3
==> Patching
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.3 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-scan-dir=/us
==> make
==> make install
==> /usr/local/Cellar/php56/5.6.3/bin/pear config-set php_ini /usr/local/etc/php/5.6/php.ini
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php5_module    /usr/local/opt/php56/libexec/apache2/libphp5.so

The php.ini file can be found in:
    /usr/local/etc/php/5.6/php.ini

✩✩✩✩ PEAR ✩✩✩✩

If PEAR complains about permissions, 'fix' the default PEAR permissions and config:
    chmod -R ug+w /usr/local/Cellar/php56/5.6.3/lib/php
    pear config-set php_ini /usr/local/etc/php/5.6/php.ini

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP56 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

To have launchd start php56 at login:
    ln -sfv /usr/local/opt/php56/*.plist ~/Library/LaunchAgents
Then to load php56 now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php56.plist
==> Summary
🍺  /usr/local/Cellar/php56/5.6.3: 496 files, 40M, built in 3.0 minutes
````

Same result when trying to install mcrypt. 

Also: 

````
$PATH = /usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin
````

**Comment by blacklizard** [comment]
@rnewton `brew update` will solve your problme

**Comment by alanthing** [comment]
Thanks @blacklizard , closing.
