### ISSUE TITLE
PHP-CS-Fixer not working for v1.6

### ISSUE THREAD

**Issue by Glavin001** [Homebrew/homebrew-php#1648]
See https://github.com/simplechris/homebrew-php/commit/b5b753d886a766d41fca83a1038b30c25297e819

> I have Homebrew version 0.9.5, PHP 5.6.7, and PHP-CS-Fixer 1.2
>
>I am trying and unable to install the latest PHP-CS-Fixer (after the pull request https://github.com/Homebrew/homebrew-php/pull/1639 to Homebrew, which simply updated from 1.2 to 1.6).
>
>Here is what is logged:
>
```bash
$ brew install php-cs-fixer
==> Installing php-cs-fixer from homebrew/homebrew-php
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
==> Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/archive/v1.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/php-cs-fixer-1.6.tar.gz
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Iterator RecursiveIteratorIterator returned a path "/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description" that is not in the base directory "/private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/src"' in /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php:9
Stack trace:
#0 /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php(9): Phar->buildFromDirectory('src')
#1 {main}
  thrown in /private/tmp/php-cs-fixer20150407-10762-1vch9p1/PHP-CS-Fixer-1.6/genphar.php on line 9
Error: No such file or directory - php-cs-fixer.phar
```
>
>Personally I am not a PHP developer and only use this package for my package https://github.com/Glavin001/atom-beautify so I am unable to assist much and do not know about the inner workings of PHP package managers and PHP-CS-Fixer.
>
>I wanted to create this in hopes that someone recognized this issue and I could update PHP-CS-Fixer.
>
>Thank you in advance!

**Comment by alanthing** [comment]
Please post full logs here for additional assistance:

```
brew gist-logs php-cs-fixer
```

**Comment by Glavin001** [comment]
`brew gist-logs php-cs-fixer` returned `Error: No logs.` :frowning: 

```bash
$ brew upgrade php-cs-fixer
==> Upgrading 1 outdated package, with result:
php-cs-fixer 1.6
==> Upgrading php-cs-fixer
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
==> Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/archive/v1.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/php-cs-fixer-1.6.tar.gz
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.6.6)
    Loading from cache

  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Installing symfony/stopwatch (v2.6.6)
    Loading from cache

  - Installing symfony/filesystem (v2.6.6)
    Loading from cache

  - Installing symfony/config (v2.6.6)
    Loading from cache

  - Installing symfony/console (v2.6.6)
    Loading from cache

  - Installing symfony/yaml (v2.6.6)
    Loading from cache

  - Installing satooshi/php-coveralls (dev-master 2fbf803)
    Cloning 2fbf803803d179ab1082807308a67bbd5a760c70

  - Installing symfony/finder (v2.6.6)
    Loading from cache

  - Installing symfony/process (v2.6.6)
    Loading from cache

  - Installing sebastian/diff (1.3.0)
    Loading from cache

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
satooshi/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
Writing lock file
Generating autoload files
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Iterator RecursiveIteratorIterator returned a path "/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description" that is not in the base directory "/private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/src"' in /private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/genphar.php:9
Stack trace:
#0 /private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/genphar.php(9): Phar->buildFromDirectory('src')
#1 {main}
  thrown in /private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/genphar.php on line 9
Error: No such file or directory - php-cs-fixer.phar

$ brew gist-logs php-cs-fixer
Error: No logs.
```

**Comment by Glavin001** [comment]
Okay, this is strange. I moved the `GitHub.app` (`/Applications/GitHub.app/`) to the trash (temporarily) and then ran `brew upgrade php-cs-fixer` and it installed correctly! Now I put back the GitHub app and PHP-CS-Fixer still works! Great! I still think this is an issue somewhere. Hopefully this helps. 
I focused on what it said in the error here:

```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Iterator RecursiveIteratorIterator returned a path "/Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description" that is not in the base directory "/private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/src"' in /private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/genphar.php:9
Stack trace:
#0 /private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/genphar.php(9): Phar->buildFromDirectory('src')
#1 {main}
  thrown in /private/tmp/php-cs-fixer20150503-49530-d4uy2h/PHP-CS-Fixer-1.6/genphar.php on line 9
Error: No such file or directory - php-cs-fixer.phar
```

**Comment by alanthing** [comment]
Can you `brew update` and try again? We're up to 1.7 now.

**Comment by tonglil** [comment]
Mm, this is happening to me when trying to upgrade from 1.7 to 1.8.1. New issue or not?

**Comment by tonglil** [comment]
Output from verbose, it is getting caught on this:
```
ln -s ../Cellar/php-cs-fixer/1.7/bin/php-cs-fixer php-cs-fixer
Error: No such file or directory - php-cs-fixer.phar
```
