### ISSUE TITLE
Cleanup not working

### ISSUE THREAD

**Issue by it-can** [Homebrew/homebrew-php#1918]
When I try to do ```brew cleanup``` I get this error:

```
Error: undefined method `strip' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/pathname.rb:396:in `abv'
/usr/local/Library/Homebrew/keg.rb:139:in `abv'
/usr/local/Library/Homebrew/cmd/cleanup.rb:96:in `cleanup_path'
/usr/local/Library/Homebrew/cmd/cleanup.rb:61:in `cleanup_keg'
/usr/local/Library/Homebrew/cmd/cleanup.rb:46:in `block in cleanup_formula'
/usr/local/Library/Homebrew/cmd/cleanup.rb:46:in `each'
/usr/local/Library/Homebrew/cmd/cleanup.rb:46:in `cleanup_formula'
/usr/local/Library/Homebrew/cmd/cleanup.rb:35:in `block in cleanup_cellar'
/usr/local/Library/Homebrew/cmd/cleanup.rb:33:in `each'
/usr/local/Library/Homebrew/cmd/cleanup.rb:33:in `cleanup_cellar'
/usr/local/Library/Homebrew/cmd/cleanup.rb:12:in `cleanup'
/usr/local/Library/brew.rb:124:in `<main>'
```

Does anybody have an idea what to do?

I am using:
- Mac OS X: 10.10.4
- Xcode latest installed (and accepted agreement)
- Homebrew 0.9.5

**Comment by ablyler** [comment]
Can you please open an issue with https://github.com/Homebrew/homebrew since this isn't php specific? Thanks!

**Comment by it-can** [comment]
Ow whoops

**Comment by it-can** [comment]
Posted in the correct repo... https://github.com/Homebrew/homebrew/issues/41925
