### ISSUE TITLE
Problem while installing python 

### ISSUE THREAD

**Issue by rudydrs** [Homebrew/homebrew-php#3484]
Rudras-MacBook-Pro:~ rudrapratapsingh$  brew install python
==> Installing dependencies for python: sqlite, makedepend
==> Installing python dependency: sqlite
==> Downloading https://sqlite.org/2015/sqlite-autoconf-3080802.tar.gz
Already downloaded: /Library/Caches/Homebrew/sqlite-3.8.8.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/sqlite/3.8.8.2 --enable-dynamic-exten
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/sqlite-Ykrody/sqlite-autoconf-3080802':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: http://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:343:in `open'
	from /usr/local/Library/Homebrew/utils.rb:375:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:403:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:145:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:141:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:180:in `dump'
	from /usr/local/Library/brew.rb:162:in `rescue in <main>'
	from /usr/local/Library/brew.rb:65:in `<main>'
Rudras-MacBook-Pro:~ rudrapratapsingh$

**Comment by rudydrs** [comment]
Resolved by installing some dependencies.
