### ISSUE TITLE
Tapping fails

### ISSUE THREAD

**Issue by PuShaoWei** [Homebrew/homebrew-php#4560]
```
"Error: invalid attribute for formula 'homebrew/php/php71': version (nil)
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formula.rb:251:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:198:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:274:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:69:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/--prefix.rb:14:in `__prefix'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Error: invalid attribute for formula 'homebrew/php/php71': version (nil)
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formula.rb:251:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:198:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:274:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:69:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/--prefix.rb:14:in `__prefix'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

**Comment by PuShaoWei** [comment]
```
🤥  pushaowei 🍭 12:15 ➜  ~ brew config
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://git.coding.net/homebrew/homebrew.git
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 6 个月前
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 8829cee9084d376e2bcee88dea73af23b609eae2
Core tap last commit: 3 天前
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

**Comment by PuShaoWei** [comment]
I don't know why

**Comment by PuShaoWei** [comment]
To solve the
``` 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
